<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class ShieldSeeder extends Seeder
{
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Create permissions
        $permissions = [
            // Resource permissions will be auto-generated by Shield
            // But we create some custom ones here
            'view_any_dashboard',
            'access_admin_panel',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // Create Super Admin Role
        $superAdminRole = Role::firstOrCreate([
            'name' => 'super_admin',
            'guard_name' => 'web',
        ]);

        // Super admin gets all permissions
        $superAdminRole->givePermissionTo(Permission::all());

        // Create Panel User Role (basic access)
        $panelUserRole = Role::firstOrCreate([
            'name' => 'panel_user',
            'guard_name' => 'web',
        ]);

        $panelUserRole->givePermissionTo([
            'view_any_dashboard',
            'access_admin_panel',
        ]);

        // Create Staff Role
        $staffRole = Role::firstOrCreate([
            'name' => 'staff',
            'guard_name' => 'web',
        ]);

        // Staff can view and create, but limited delete
        $staffRole->givePermissionTo([
            'view_any_dashboard',
            'access_admin_panel',
        ]);

        // Create Viewer Role (read-only)
        $viewerRole = Role::firstOrCreate([
            'name' => 'viewer',
            'guard_name' => 'web',
        ]);

        $viewerRole->givePermissionTo([
            'view_any_dashboard',
            'access_admin_panel',
        ]);

        // Create Super Admin User
        $superAdmin = User::firstOrCreate(
            ['email' => 'admin@tracerstudy.test'],
            [
                'name' => 'Super Admin',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]
        );

        $superAdmin->assignRole($superAdminRole);

        // Create Demo Staff User
        $staff = User::firstOrCreate(
            ['email' => 'staff@tracerstudy.test'],
            [
                'name' => 'Staff User',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]
        );

        $staff->assignRole($staffRole);

        // Create Demo Viewer User
        $viewer = User::firstOrCreate(
            ['email' => 'viewer@tracerstudy.test'],
            [
                'name' => 'Viewer User',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]
        );

        $viewer->assignRole($viewerRole);

        $this->command->info('Shield seeding completed!');
        $this->command->info('');
        $this->command->info('Login credentials:');
        $this->command->info('===================');
        $this->command->info('Super Admin: admin@tracerstudy.test / password');
        $this->command->info('Staff: staff@tracerstudy.test / password');
        $this->command->info('Viewer: viewer@tracerstudy.test / password');
    }
}
