repos:
  - repo: local
    hooks:
      - id: php-lint
        name: PHP Lint
        entry: vendor/bin/pint --test
        language: system
        files: \.php$
        
      - id: phpstan
        name: PHPStan Static Analysis
        entry: vendor/bin/phpstan analyse --no-progress
        language: system
        files: \.php$
        
      - id: php-tests
        name: PHP Tests
        entry: php artisan test
        language: system
        files: \.php$
        pass_filenames: false
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
